List_Products = '/products/'
Retrieve_Product = '/products/:product-id'
Create_Product = '/products/new'
Update_Product = '/products/update/:product-id'
Delete_Product = '/products/delete/:product-id'
