version: '2.17.2'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    command: /bin/sh ./run-app.sh
  
  database:
    container_name: database
    image: postgres:13
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_13_06_2024
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
